### ISSUE TITLE
Image for SLES12 SP4 JeOS GM unavailable on download.suse.de

### ISSUE THREAD

**Issue by vandabarata** [uyuni-project/sumaform#1171]
Right now, it seems all the images for SLES12SP4 have been removed from `download.suse.de`, including the one in the title which is used by the cucumber testsuite module (https://download.suse.de/install/SLE-12-SP4-JeOS-GM/SLES12-SP4-JeOS.x86_64-12.4-OpenStack-Cloud-GM.qcow2). I'm unsure of the reason and have e-mailed the auto-build team on the 27th of September, with no reply as of yet. So, to ensure the sumaform deployments keep working, we need to use mirrors where the needed images are still hosted, or to filter for specific images for our deployments and not include this one.

**Comment by juliogonzalez** [comment]
@vandabarata autobuild is short on people, so it seems they are overloaded.

Send them a reminder.

However I seem to remember someone else saw this issue before, and autobuild told the images were moved somewhere else? Maybe you want to ask at #team-susemanager
