### ISSUE TITLE
New sumaform module to deploy a DHCP Server

### ISSUE THREAD

**Issue by srbarrios** [uyuni-project/sumaform#1451]
# Description

We will require it in our Retail Branch Server containerized.

# Tasks

# Links
- https://github.com/uyuni-project/sumaform/pull/1525

**Comment by Bischoff** [comment]
Question: in a separate VM, or on the branch server (aka proxy)?

PRO separate machine:
 * more realistic: the end users will be using their own DNS/DHCP instances, and not will have a new one inside the retail branch server
 * having it separated allows it to be ONLY in private network, which is better to avoid DHCP packets leakage

CON separate machine:
 * yet another VM

I think I will go for a separate machine

**Comment by Bischoff** [comment]
Strictly speaking, this new module is finished. I just don't merge it yet because I need to adapt the test suite to the new situation (issue )
