### ISSUE TITLE
JEOS enablement in sumaform

### ISSUE THREAD

**Issue by MalloZup** [uyuni-project/sumaform#434]
So this is follow-up from #432  since it was too much risky to add JEOS clients and ubuntu ones.

# what to do:

- [ ] find a mechanism to install `qemu-agent`  on various SLES  clients. ( qemu-guest agent is not provided by default)
- [ ] run the testsuite and see if all JEOS images are ok
- [ ]  optionally do it for centos7

**Comment by Bischoff** [comment]
@rjmateus is this finished ? if yes we might close this card

**Comment by rjmateus** [comment]
I think It is @Bischoff 

> find a mechanism to install qemu-agent on various SLES clients. ( qemu-guest agent is not provided by default)

We have now support for JEOS. But the first item I'm not sure I understand it. @moio do you agree this can be closed?

**Comment by MalloZup** [comment]
we can close this issue.

https://github.com/uyuni-project/sumaform/blob/master/backend_modules/libvirt/base/main.tf#L14


The `qemu-agent` is needed because at that time, historically we used bridge mode. I think since you have the PR merged , you find out a mechanism or network setup to get the ips without the qemu-agent . 
I"m closing this because it solved.

The qemu-agent step is only a detail which I think you have managed to solve. thx

**Comment by Bischoff** [comment]
> The `qemu-agent` is needed because at that time, historically we used bridge mode. I think since you have the PR merged , you find out a mechanism or network setup to get the ips without the qemu-agent .

Well, we can get IPs without qemu-agent. But it's way slower. I am pretty sure we still use qemu-agent, event on JeOS. How this is exactly done is mistery to me, however.


> I"m closing this because it solved.
> 
> The qemu-agent step is only a detail which I think you have managed to solve. thx

OK.

**Comment by gmoro** [comment]
Just a note here, qemu-guest-agent is installed by default in SLE15-SP2 onwards and in TW and Leap 15.2 as well

**Comment by Bischoff** [comment]
Also, I found this is done in the provider, not in sumaform. So there was never anything to do at sumaform level :trollface:

**Comment by MalloZup** [comment]
yeah I think it got fixed on sle15sp2, thx didn't know
