### ISSUE TITLE
salt-netapi-client cannot execute runner calls

### ISSUE THREAD

**Issue by cbbayburt** [uyuni-project/sumaform#450]
The runner calls from `salt-netapi-client` fail with the following error in SUSE Manager servers created with sumaform:
```
com.suse.salt.netapi.exception.SaltException: Response code: 500
```
The reason I believe this is a sumaform issue is that when I restart spacewalk services and specifically `salt-api`, the problem is gone forever. It could be a problem with the initial startup.

### How to reproduce
1. Create a new SUSE Manager instance with sumaform (version: 3.2 or Uyuni)
2. Have the system execute a runner call:
    In my case, I registered a working Kubernetes VHM to SUMA. Then in the VHM details page, when I click `Refresh Data`, SUMA tries to make the runner call: `mgrk8s.get_all_containers`.
3. Check the `rhn_web_ui.log`

I didn't have enough time to find the root cause for this. The netapi client doesn't say much more about the runner calls, but it seems to be consistent in all created servers.

**Comment by cbbayburt** [comment]
> Could you please share /var/log/salt/api?

No errors there. The log is empty. I'll try with `DEBUG` level next time I setup a new server.

**Comment by moio** [comment]
Do you have news @cbbayburt ?

**Comment by cbbayburt** [comment]
> Do you have news @cbbayburt ?

I've not come across the problem for a long time. Let me be optimistic and close the issue for now. I'll update whenever I get my hands on a k8s cluster next time.
