### ISSUE TITLE
Provisioning of uyuni/suma4 with synchronized channels does not work

### ISSUE THREAD

**Issue by aaannz** [uyuni-project/sumaform#522]
I don't know if this is a sumaform bug, or suma4/uyuni bug.
There is a problem that `/usr/bin/env python` call in [wait_for_mgr_sync.py](https://github.com/moio/sumaform/blob/master/salt/suse_manager_server/wait_for_mgr_sync.py#L1) returns python2 instead of python3. But all SUMA/uyuni python modules are already for python3 in different search path so the script the fails with the unknown module error.

This may be misconfiguration of default python in base image or if the default python is indeed correct, then there is a bug in sumaform which I'm yet to find out how to solve correctly.

Any ideas?

**Comment by juliogonzalez** [comment]
IIRC, for Leap15 and SLE 15 we need to use `#!/usr/bin/python3`as shebang.

The problem is that it seems https://github.com/moio/sumaform/blob/master/salt/suse_manager_server/wait_for_mgr_sync.py#L1 is not tied to the OS version, so maybe we'll need two variants.

**Comment by juliogonzalez** [comment]
Confirmed, the shebang is wrong if you want python3.

See for example: https://github.com/uyuni-project/uyuni/blob/master/susemanager/src/mgr-create-bootstrap-repo

**Comment by aaannz** [comment]
That's how I did my workaround. I just was not sure how to fix this. So two variants is the way to go?

Btw. Do you know why `/usr/bin/env python` does not point to python3 if python3 is supposed to be default? I'm pretty sure this worked for me before.

**Comment by juliogonzalez** [comment]
Personally, as I think the script is valid for both python2 and python3, I'd change it to a template and would fill the shebang depending on the OS. Not sure if this the approach @moio likes more. Or changing the file after it's installed, according to the OS.

Having two variants means maintaining two scripts.

**Comment by moio** [comment]
> Not sure if this the approach @moio likes more.

I do not like the approach very much but I have been told by Python experts this is the only right way.

Eg. https://github.com/moio/sumaform/blob/master/salt/default/set_ip_in_etc_hosts.py.jinja#L1

I will accept this bugfix, of course, and be even happier to learn about any more elegant alternative way, if one exists.

**Comment by aaannz** [comment]
This is already fixed by templating. Closing.
