### ISSUE TITLE
terraform V12 errors

### ISSUE THREAD

**Issue by MalloZup** [uyuni-project/sumaform#547]
Hi I'm running locally terraformV12 with a custom provider libvirt builded against TF12,

It seems that terraform has now new reserved vars. e.g `count`

It might be other errors, I just tried it out. Feel free to use this issue as epic.

 HTH
```
Error: Reserved argument name in module block

  on main.tf line 40, in module "client":
  40:   count = 1

The name "count" is reserved for use in a future version of Terraform.


Error: Reserved argument name in module block

  on main.tf line 51, in module "minion":
  51:   count = 1

The name "count" is reserved for use in a future version of Terraform.
```

**Comment by moio** [comment]
Thanks for reporting.

Wow, 0.12 is finally out! So nice they released it on my birthday. What a present, and I wasn't even aware!


Unless we get very major stability problems migration to 0.12 is something I regard as pretty important, changes and extensions to the language are very important for sumaform. I do not know yet when that will happen, but still, I hope, that will be soon.

**Comment by MalloZup** [comment]
yop no pb.

We want to release soonish a next version for terraform-libvirt. 

After this release we plan to go to `0.12` major version. I agree that the 0.12 make life easier in many concern so we want to go there soonish. We have already a PR pending. (see upstream). :poodle:

**Comment by MalloZup** [comment]
https://github.com/dmacvicar/terraform-provider-libvirt/pull/609

**Comment by MalloZup** [comment]
@moio  we merged upstream the terraform V12 on libvirt.

SO one could build from source the plugin from master and use it with v12 already. This will work and all test are passing.

I was asking me if we should maybe create in rocketchat a TF-12 channel so we could join/share knowledge with the tf12 changes and tipps/tricks etc..
