### ISSUE TITLE
Mirror contains 23 GB of duplicated RPMs

### ISSUE THREAD

**Issue by mbologna** [uyuni-project/sumaform#586]
```
mirror:~ # jdupes -r /srv/mirror/ -m -M -s -S
[...]
23154 duplicate files (in 13589 sets), occupying 23368 MB
```

These duplicates are all RPMs that are duplicated between directories, e.g.

```
/srv/mirror/SUSE/Products/SUSE-Manager-Server/3.0/x86_64/product/x86_64/python-gpgme-0.1-1.17.x86_64.rpm
/srv/mirror/SUSE/Products/SUSE-Manager-Server/3.1/x86_64/product/x86_64/python-gpgme-0.1-1.17.x86_64.rpm
/srv/mirror/SUSE/Products/SUSE-Manager-Server/3.2/x86_64/product/x86_64/python-gpgme-0.1-1.17.x86_64.rpm
```

Solutions:

- use jdupes to link the "old" references (the ones found in older products) to the newest one
Drawback: when an RPM is deleted, the links are dangling
- use btrfs in-band deduplication: still experimental
- use ZFS deduplication: still experimental

Do you have any other ideas?

**Comment by moio** [comment]
`jdupes --linkhard` should do the trick, right?

https://en.wikipedia.org/wiki/Hard_link#Link_counter

**Comment by mbologna** [comment]
I confirm and it is working!
Would a PR to fetch jdupes and run it as the last step of mirror.sh be welcome?

**Comment by moio** [comment]
Absolutely!
