### ISSUE TITLE
Do not set up the SCC credentials in the test suite case

### ISSUE THREAD

**Issue by Bischoff** [uyuni-project/sumaform#672]
In the test suite, we have a scenario to test real SCC credentials. Currently it's green, but testing nothing, because the SCC credentials are already there from sumaform.

Perharps the solution is to not set this up at sumaform level. Not sure. Needs some investigation.

Ping @mseidl .

**Comment by moio** [comment]
AFAIK, SCC credentials are currently required by the SUSE Manager installer. You can try removing them from the bottom of:

https://github.com/uyuni-project/sumaform/blob/master/salt/suse_manager_server/setup_env.sh

And see if the installation procedure works. If it does not, then this is not actionable from a sumaform perspective.

**Comment by Bischoff** [comment]
OK.

I have added today a check in the test suite that the SCC credentials are valid. So now it's less useless a scenario.

Let's close it then.
