### ISSUE TITLE
How to use public downloadable image ? 

### ISSUE THREAD

**Issue by vijaigan** [uyuni-project/sumaform#738]
Error: Error while determining image type for http://download.suse.de/ibs/Devel:/Galaxy:/Terraform:/Images/images/sles12sp3.x86_64.qcow2: Get
 http://download.suse.de/ibs/Devel:/Galaxy:/Terraform:/Images/images/sles12sp3.x86_64.qcow2: dial tcp: lookup download.suse.de: no such host

  on backend_modules/libvirt/base/main.tf line 39, in resource "libvirt_volume" "volumes":
  39: resource "libvirt_volume" "volumes" {

Error: Error while determining image type for https://download.suse.de/install/SLE-15-SP2-JeOS-GM/SLES15-SP2-JeOS.x86_64-15.2-OpenStack-Cloud
-GM.qcow2: Get https://download.suse.de/install/SLE-15-SP2-JeOS-GM/SLES15-SP2-JeOS.x86_64-15.2-OpenStack-Cloud-GM.qcow2: dial tcp: lookup dow
nload.suse.de: no such host

  on backend_modules/libvirt/base/main.tf line 39, in resource "libvirt_volume" "volumes":
  39: resource "libvirt_volume" "volumes" {

-------------------

I am getting the above issue and after reading the "Contributing Guidelines" I have understood , the http:://download.suse.de is only internal to SUSE employees. 

How can I use the public available download image in this terraform ?

**Comment by rjmateus** [comment]
Hey @vijaigan, thanks for your feedback

Which images were you planing to use? Just sles12sp3 adn sles15-sp2? 
At the moment sles images are only available for suse employees in the context of this project.

If you want to contribute/setup [uyuni](https://github.com/uyuni-project/uyuni) you can use free images, like Leap, centos or ubuntu. Have a look at the following example: https://github.com/uyuni-project/sumaform/blob/master/main.tf.uyuni.example

**Comment by moio** [comment]
@rjmateus we could support JeOS images from here:

https://www.suse.com/download/sles/

That would mean to either use evaluation copies or register to SCC if the customer has valid SCC credentials.

I think this would be good in general - it's just not implemented as of today.

@vijaigan feel free to try out if they work and report back!

**Comment by renner** [comment]
Closing as the original question has long been answered.
