### ISSUE TITLE
broken link on doc

### ISSUE THREAD

**Issue by MalloZup** [uyuni-project/sumaform#739]
this is a broken link https://doc.opensuse.org/documentation/leap/virtualization/html/book.virt/cha.libvirt.networks.html#libvirt.networks.bridged

from 
https://github.com/uyuni-project/sumaform/blob/master/backend_modules/libvirt/README.md

set up bridged networking:

    ensure your target libvirt host has a bridge device on the network you want to expose your machines on (openSUSE instructions Ubuntu instructions)

**Comment by rjmateus** [comment]
thanks @MalloZup 
The link was replaced to point to the correct location. I will close the issue.
