### ISSUE TITLE
Migrate to terraform 0.13

### ISSUE THREAD

**Issue by rjmateus** [uyuni-project/sumaform#762]
Terraform 0.13 is now available [1] and some changes may be needed on this project in order to support it. This issue intends to track which changes needs to be done.

Libvirt provider support:
https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/docs/migration-13.md

[1] https://www.hashicorp.com/blog/announcing-hashicorp-terraform-0-13/

**Comment by rjmateus** [comment]
ping @juliogonzalez @moio

**Comment by aplanas** [comment]
My devel machine is TW, and is in 0.13.3. Any progress here?

**Comment by rjmateus** [comment]
We didn't make any progress in this regard, and we cannot say when it will be added on the loop

**Comment by wombelix** [comment]
Disclaimer: Quick & dirty / hacky Workaround, was fine for me to deploy a local Uyuni Dev Environment on my laptop with libvirt.

I'm using Terraform v0.14.5 on openSUSE Tumbleweed (20210212) and was overwriting the required_version parameter as well forced terraform to use the global plugin path.


1) Install terraform and the libvirt provider
`sudo zypper in terraform terraform-provider-libvirt`

2) Add terraform.rc file into sumaform root folder to define a local plugin path

terraform.rc
```
provider_installation {
  filesystem_mirror {
    path = "/usr/share/terraform/plugins"
  }
}
```

3) create / adjust main.tf based on your needs

4) Check were 'hashicorp/libvirt' will be required and place a override.tf in each location to use 'dmacvicar/libvirt' instead.
`terraform providers`

override.tf
```
terraform {
  required_version = ">= 0.14"
  required_providers {
    libvirt = {
      source  = "dmacvicar/libvirt"
      version = "0.6.3"
    }
  }
}
```

5) Lot of terraform version related errors will show up, add a override.tf file into each mentioned folder to get rid of them.
`terraform init`

```
terraform {
  required_version = ">= 0.14"
}
```

So far it seems like that the necessary sumaform adjustments might limited to handling the new registry namespace stuff accordingly.

**Comment by nodeg** [comment]
Closing this since we already use version 1.0.10
