### ISSUE TITLE
Issue with extra_swapfile with a controller module not modified by cucumber_testsuite module

### ISSUE THREAD

**Issue by srbarrios** [uyuni-project/sumaform#768]
Hi there,

I'm not sure if this is a bug in sumaform, but I found that the controller deployed through cucumber_testsuite module has `swap_file_size` as null https://github.com/uyuni-project/sumaform/blob/e3272fc49326074e90dd0efae1d0bdad05aa52fe/modules/cucumber_testsuite/main.tf#L279, so it doesn't enter in this statement https://github.com/uyuni-project/sumaform/blob/b07a40137e34ac9ee4419af373c5706fcb54a342/salt/default/init.sls#L17 but if we use a custom main.tf without cucumber_testsuite wrapper, and therefore a separated controller instantiation, by default the value of this variable is 4GB. 

And for some some reason, it cause this issue:
``` [2020-09-08T10:07:26.763Z] [0m[0mmodule.controller.module.controller.module.host.null_resource.provisioning[0] (remote-exec):     [0;31m      ID: file_swap[0;0m
[2020-09-08T10:07:26.763Z] [0m[0mmodule.controller.module.controller.module.host.null_resource.provisioning[0] (remote-exec):     [0;31mFunction: mount.swap[0;0m
[2020-09-08T10:07:26.763Z] [0m[0mmodule.controller.module.controller.module.host.null_resource.provisioning[0] (remote-exec):     [0;31m    Name: /extra_swapfile[0;0m
[2020-09-08T10:07:26.763Z] [0m[0mmodule.controller.module.controller.module.host.null_resource.provisioning[0] (remote-exec):     [0;31m  Result: False[0;0m
[2020-09-08T10:07:26.763Z] [0m[0mmodule.controller.module.controller.module.host.null_resource.provisioning[0] (remote-exec):     [0;31m Comment: Swap /extra_swapfile failed to activate. Added new entry to the fstab.[0;0m```

**Comment by moio** [comment]
OK, this is interesting.

First question is: do you think we need any swapfile? If not, it'd make sense to change the default.

Second question: do you have the full salt output? Normally in the section before results more output is produced for each state - and I hope to find out there what is the reason for the activation failure.

Another option - if easier to you - is just to tell an address to SSH into such a machine.

**Comment by srbarrios** [comment]
> OK, this is interesting.
> 
> First question is: do you think we need any swapfile? If not, it'd make sense to change the default.
> 
> Second question: do you have the full salt output? Normally in the section before results more output is produced for each state - and I hope to find out there what is the reason for the activation failure.
> 
> Another option - if easier to you - is just to tell an address to SSH into such a machine.

No, I don't think we need a swapfile by default in the controller. So maybe better deactivate it by default with a null value.
About how to debug it, it is easy, you just need a controller defined in your local main.tf, without the use of the cucumber_testsuite module.
