### ISSUE TITLE
Get rid of mirror.sh

### ISSUE THREAD

**Issue by Bischoff** [uyuni-project/sumaform#798]
As discussed in infra meeting, I would like to remove `mirror.sh` (sumaform's file `salt/mirror/mirror.sh`).

This wrapper script is, in my opinion, horrible. It mixes a lot of different things under one roof, and then adds the same number of command line options to access those things separately again.

To make things even worse, in our mirrors, configuration files are sparse here and there, some of them being in dot-directories, i.e. hidden. Finally, we call it from a crontab attached to root user, a method which I would qualify as "hiding" too.

I suggest simply removing it from sumaform. Then, on our mirrors, I would do the same I did for QAM:
 * have one script in `/etc/cron.daily` for each task we want to perform
 * have one configuration file in `/etc` for each of the functions of the mirror

This is both simple and obeying standard paths and practices. See https://gitlab.suse.de/galaxy/infrastructure/-/blob/master/srv/salt/minima-qam/README.md for details.

If accepted, I can take care of the implementation.

**Comment by rjmateus** [comment]
I'm not against it.
Those new files will be placed on sumaform also? A mirror is not also used in the test suite be can be also used locally for developers to speedup machine bootstrap. For this reason should be possible to easily deploy a mirror without manual steps.

**Comment by moio** [comment]
@rjmateus well, this being a sumaform issue I would expect to be implemented in the form of a sumaform PR :wink: 

@Bischoff I understand and agree with the principles. Had to do some digging myself at times, and found it more complicated than needed.

One (naive) question: keeping the same idea, what pros and cons would you see with using `systemd` units as a potential alternative for `cron`?

**Comment by Bischoff** [comment]
> One (naive) question: keeping the same idea, what pros and cons would you see with using `systemd` units as a potential alternative for `cron`?

That's not a naive question. That was my intended next step... But let's do one thing at once please, i'm not familiar with systemd timers yet.

**Comment by Bischoff** [comment]
So we do not get any regret... :trollface: 

This script just changed a whole `/` filesystem to `rwxrwxrwx` permissions.... it happens when mirror directory does not pre-exist :smile:

**Comment by Bischoff** [comment]
> I'm not against it.
> Those new files will be placed on sumaform also? A mirror is not also used in the test suite be can be also used locally for developers to speedup machine bootstrap. For this reason should be possible to easily deploy a mirror without manual steps.

Yes, sorry. That was intended, and I should have said it.

**Comment by moio** [comment]
> That's not a naive question. That was my intended next step... But let's do one thing at once please, i'm not familiar with systemd timers yet.

It's actually very easy, and I will welcome both the two-step and the one-step approach as you prefer.

Just to give you an inspiration, this is how you set up a daily execution of a command:

https://github.com/moio/pase/blob/master/terraform/salt/pase/init.sls#L59-L71
https://github.com/moio/pase/blob/master/utils/pase-index.timer
https://github.com/moio/pase/blob/master/utils/pase-index.service

One nice thing is that logging comes for free courtesy of `journalctl`, and also locking (it won't fire twice concurrently).

Thanks, and always remember to have fun!

**Comment by moio** [comment]
PS. @juliogonzalez, as the main author of the current script, do you see any important downsides to this effort?

**Comment by juliogonzalez** [comment]
TBW, I just did a refactor, so we could use parameters and to make more flexible... and that was the approach I followed as a I didn't have more time for more improvements.

For our usage, I do not see any downsides, and I don't care much about using cron or systemd, as long as:

- We can easily configure things if there are failures (as it's the case now for the internal mirrors), can systemd do that as cron does?
- There are still configuration files to adjust the things as needed. Remember that for the internal infra we have a setup slightly different from what provides as a mirror.
- There's an easy way of launching the different scripts without systemd or crond (in case a sync needs to be forced)
- This is documented, both for us, and for sumaform users that want to manually refresh  their mirrors

**Comment by Bischoff** [comment]
> * We can easily configure things if there are failures (as it's the case now for the internal mirrors), can systemd do that as cron does?

No idea.

> * There are still configuration files to adjust the things as needed. Remember that for the internal infra we have a setup slightly different from what provides as a mirror.

Yes. All in `/etc` now.

> * There's an easy way of launching the different scripts without systemd or crond (in case a sync needs to be forced)

Easier than before, just run the script in `/etc/cron.daily`.

> * This is documented, both for us, and for sumaform users that want to manually refresh  their mirrors

It's documented in QAM, I can copy it in QA mirrors. For sumaform I don't know, but it has to be done for sure.

**Comment by moio** [comment]
Responding from a `systemd` angle:

>     * We can easily configure things if there are failures (as it's the case now for the internal mirrors), can systemd do that as cron does?

What do you mean exactly?

>     * There are still configuration files to adjust the things as needed. Remember that for the internal infra we have a setup slightly different from what provides as a mirror.

Configuration files are outside of `systemd`, so no difference expected.

>     * There's an easy way of launching the different scripts without systemd or crond (in case a sync needs to be forced)

`systemctl start <service>`

Or, anyway, I expect the `ExecStart` line to be executable manually.

>     * This is documented, both for us, and for sumaform users that want to manually refresh  their mirrors

Also my expectation regardless `systemd`.


@Bischoff I think you have a go

**Comment by juliogonzalez** [comment]
> * We can easily configure things if there are failures (as it's the case now for the internal mirrors), can systemd do that as cron does?

"things to send email" :-)

Configuring that with cron is more less "easy": use MAILTO on the config file, and have your scripts produce logs only if there are errors.

No idea of what happens with systemd timers.

> systemctl start <service>

I guess you mean timer. But anyway, we'll need documentation as there will be several timers IIUC.

**Comment by Bischoff** [comment]
> @Bischoff I think you have a go

Thanks everyone. I'll try to sneak this in whenever possible.

**Comment by Bischoff** [comment]
Now 4.2 is out, jumping into it again. I will create another issue in SUSE/spacewalk so we have it in our board as well.

**Comment by Bischoff** [comment]
Done: #917 

I still have to fix manually the two CI mirrors that are already deployed though.
