### ISSUE TITLE
Different switches for SUMA/Uyuni disk mirror implementation and the mirror used during deployment phase

### ISSUE THREAD

**Issue by srbarrios** [uyuni-project/sumaform#859]
Currently, if we want to use a Minima mirror only to configure SUSE Manager to download the content from a mirror, so rhn.conf, we can't; we are forced to also mirror everything that sumaform needs during the automatic configuration phase, so during salt states in Sumaform, where tons of temporary repositories are set up.

I would like to have a different variable to use only for disk mirror feature on SUMA, when syncing products from SCC.

So, this salt states:
https://github.com/uyuni-project/sumaform/blob/master/salt/server/rhn.sls#L41-L69

**Comment by srbarrios** [comment]
@rjmateus @moio if you both agreed on this need, I will find time to implement it.

**Comment by moio** [comment]
What is the use case you are trying to achieve? Deploy Servers without a mirror but only consume content from a mirror?

If that is the case then yes, I am not against it.

**Comment by srbarrios** [comment]
Exactly, so I want to avoid mainting in the mirror for QA Maintenance tests the repositories used by Sumaform, and only maintain the repositories from SCC products, to avoid consume too much network traffic in our QAM test suite runs, when SUMA server sync all the products supported by our test suite.

**Comment by moio** [comment]
Feel free to go ahead
