### ISSUE TITLE
Add LTSS repos in products 15sp0 and 15sp1

### ISSUE THREAD

**Issue by ktsamis** [uyuni-project/sumaform#862]
We added `python3-distro` as requirement for latest salt that will be released in a couple of days. This for 15sp0 only exists in LTSS repository. So any deployment for 15sp0 beta will fail in a few days. We should add LTSS to the repos added from salt to prevent this and also do the same for 15sp1 so we don't bump into any of these issues later.

**Comment by rjmateus** [comment]
Repository location: 
http://download.suse.de/ibs/SUSE/Updates/SLE-Product-SLES/15-LTSS/x86_64/update/ http://download.suse.de/ibs/SUSE/Updates/SLE-Product-SLES/15-SP1-LTSS/x86_64/update/

Should be assigned to 
- manager 4.0 (which is running on sles15sp1)
- all minions/clients with sles15sp0 and sles15sp1
