### ISSUE TITLE
SLE11 SP4 image is broken

### ISSUE THREAD

**Issue by Bischoff** [uyuni-project/sumaform#887]
In SLE11 SP4, the version of kernel (from initrd) and modules do not match:
```
ebi5-minion:~ # grep PRETTY /etc/os-release 
PRETTY_NAME="SUSE Linux Enterprise Server 11 SP4"

ebi5-minion:~ # ls /lib/modules
3.0.101-108.126-default

ebi5-minion:~ # uname -a
Linux ebi5-minion 3.0.101-63-default #1 SMP Tue Jun 23 16:02:31 UTC 2015 (4b89d0c) x86_64 x86_64 x86_64 GNU/Linux

ebi5-minion:~ # depmod
WARNING: Couldn't open directory /lib/modules/3.0.101-63-default: No such file or directory
FATAL: Could not open /lib/modules/3.0.101-63-default/modules.dep.temp for writing: No such file or directory
```

This, under some circumstances, can result in DHCP not working after a reboot, or serial console not work, or other problems.

Root cause is the content of `/boot/grub/menu.lst`:
```
title sles11sp4_[_VMX_]
 root (hd0,0)
 kernel /boot/linux.vmx vga=0x314 splash=silent console=tty0 console=ttyS0,115200 root=/dev/vda1 disk=/dev/vda nomodeset elevator=noop showopts
 initrd /boot/initrd.vmx
 ```
If I use normal kernel and initrd instead of `linux.vmx` and `initrd.vmx`, there is no problem.

I will write a workaround for sumaform, but it would be better to fix the issue at image generation time.

Ping @moio for awareness.

**Comment by moio** [comment]
Hmm, interesting.

There is something I am missing, why do you mention packer?

**Comment by Bischoff** [comment]
Because I am lost in your images creation procedures... :-P

**Comment by Bischoff** [comment]
I reverted my patch because apparently i missed something about the initial state about deployment, but we definitely need to fix this. I will look more calmly after GMC.

**Comment by Bischoff** [comment]
Still not working, closing in favour of #936
