### ISSUE TITLE
Add amazon linux 2 to sumaform inventory

### ISSUE THREAD

**Issue by maximenoel8** [uyuni-project/sumaform#906]
The idea is to use https://cdn.amazonlinux.com/os-images/2.0.20210525.0/kvm/ to add amazon linux 2 to minion that can be deployed by sumaform.

**Comment by maximenoel8** [comment]
For now I'm hitting this error : 

```

Error: Error: couldn't retrieve IP address of domain.Please check following: 
1) is the domain running proplerly? 
2) has the network interface an IP address? 
3) Networking issues on your libvirt setup? 
 4) is DHCP enabled on this Domain's network? 
5) if you use bridge network, the domain should have the pkg qemu-agent installed 
IMPORTANT: This error is not a terraform libvirt-provider error, but an error caused by your KVM/libvirt infrastructure configuration/setup 
 timeout while waiting for state to become 'all-addresses-obtained' (last state: 'waiting-addresses', timeout: 5m0s)

  on /home/mnoel/sumaform/backend_modules/libvirt/host/main.tf line 67, in resource "libvirt_domain" "domain":
  67: resource "libvirt_domain" "domain" {
```

**Comment by rjmateus** [comment]
Are you deploying locally using libvirt backend?
Are you using avahi?
Could you check if the following packages are installed: "avahi", "nss-mdns", "qemu-guest-agent"?
You may need to configure cloud-init for this image/OS to install some extra packages or do any extra procedure to make the machine available on the local network.

You can have a look in here: https://github.com/uyuni-project/sumaform/blob/master/backend_modules/libvirt/host/user_data.yaml

**Comment by maximenoel8** [comment]
Indeed the issue came from qemu guest. I'm trying to solve some compatibility issues now.

**Comment by maximenoel8** [comment]
I was able to install the different packages needed with cloud init.
Unfortunately, during the salt execution, I have a new error because of unrecognized repositories.
I think this repositories come from repos/default.sls
```
http://download.suse.de/ibs/SUSE/Updates/RES/2-CLIENT-TOOLS/x86_64/update/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
http://download.suse.de/ibs/SUSE/Updates/RES/2-CLIENT-TOOLS/x86_64/update/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
http://download.suse.de/ibs/Devel%3A/Galaxy%3A/Manager%3A/Head%3A/RES2-SUSE-Manager-Tools/SUSE_RES-2_Update_standard/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
```
