### ISSUE TITLE
[AWS][block] opensuse153 AMI doen't match

### ISSUE THREAD

**Issue by maximenoel8** [uyuni-project/sumaform#907]
Using the aws backend to deploy server will not be possible because of opensuse 15.3 ami is not correctly configure.

```
Error: Your query returned no results. Please change your search criteria and try again.

  on /home/maxime/github/sumaform/backend_modules/aws/base/main.tf line 85, in data "aws_ami" "opensuse153":
  85: data "aws_ami" "opensuse153" {
```

**Comment by maximenoel8** [comment]
When I search for `openSUSE-Leap-15-3-v`, I only have offers from the AWS market and none from the community. 
It seems using the image from AWS marketplace doesn't fix the issue

**Comment by rjmateus** [comment]
What is the error you are getting when using the image from the marketplace?

**Comment by agraul** [comment]
As far as I know, the official openSUSE Leap 15.3 AMI is not published yet. This is out of our control, SUSE's Public Cloud team maintains those images. Last I've asked them, they did not have an ETA yet.

**Comment by maximenoel8** [comment]
The error I have is this one : 
```
Error: Your query returned no results. Please change your search criteria and try again.

  on /home/maxime/github/sumaform/backend_modules/aws/base/main.tf line 85, in data "aws_ami" "opensuse153":
  85: data "aws_ami" "opensuse153" {
```

**Comment by maximenoel8** [comment]
I tried to use the version available on the market place by changing the owner code but I still have this issue.
Indeed I need to subscribe to it so I can use it.
For my deployment, I completely remove opensuse153 references because it blocks the terraform execution.

Should I do a PR to remove it and add a card on block about opensuse153 ?

**Comment by rjmateus** [comment]
If is blocking the deployment please remove it and add a card as you suggested.

**Comment by juliogonzalez** [comment]
@maximenoel8 is this still a thing? I am now deploying https://github.com/uyuni-project/sumaform/pull/989 using an openSUSE Leap 15.3 image at AWS, and it works just fine.

**Comment by juliogonzalez** [comment]
Ping @maximenoel8

**Comment by maximenoel8** [comment]
Yes sorry, now opensuse 15.3 is available on AWS. I'm writing a PR for controller that will include opensuse 15.3
