### ISSUE TITLE
Server deployment on AWS fail using mirror because of LTS repo

### ISSUE THREAD

**Issue by maximenoel8** [uyuni-project/sumaform#908]
After creating a mirror using repositories describe in salt/mirror/minima.yaml, I'm not able to deploy the server.
Indeed one of the repositories is missing : 
` http://{{ mirror} }/ibs/SUSE/Updates/SLE-Product-SLES/15-SP2-LTSS/x86_64/update/ `

This repo seems to be set in repo/default.sls. After more investigation, this repo on download.suse.de seems to be empty.

Do we really need this repository for the deployment ? Could it be remove ?

I also tried to add this repo to the http section of minima as : 
```
http:
  - url: https://download.suse.de/ibs/SUSE/Updates/SLE-Product-SLES/15-SP2-LTSS/x86_64/update
```

When I run the command : 
```
bash mirror.sh --minima-sync=/root/.minima/minima.yaml
```

The script doesn't create the tree locally.

**Comment by maximenoel8** [comment]
@ktsamis Is it ok to remove LTSS repo for 15sp2 ?

I think you forget to add some of the repos from default.sls to the mirror minima,

**Comment by juliogonzalez** [comment]
I think this is not really a sumaform problem, but a mirror problem at SUSE itself. The `minimal.yaml` file here is *not* used for our mirrors.
