### ISSUE TITLE
Failures when downloading a opensuse153o image

### ISSUE THREAD

**Issue by calancha** [uyuni-project/sumaform#922]
We have seen errors like this:
```
'file_|-disk-image-template.qcow2_|-/var/testsuite-data/disk-image-template.qcow2_|-managed': {'changes': {}, 'comment': 'Failed to cache https://download.opensuse.org/distribution/leap/15.3/appliances/openSUSE-Leap-15.3-JeOS.x86_64-OpenStack-Cloud.qcow2: Error: HTTP 404: Not Found reading https://download.opensuse.org/distribution/leap/15.3/appliances/openSUSE-Leap-15.3-JeOS.x86_64-OpenStack-Cloud.qcow2', 'name': '/var/testsuite-data/disk-image-template.qcow2', 'result': False,
```

in the latest CI runs.

As a workaround, to have deployments again we have open:
https://github.com/uyuni-project/sumaform/pull/921

The purpose of this card is discussing a long term solution.

**Comment by moio** [comment]
@juliogonzalez am I right in saying the only ones who can actually fix the root-cause issue are the openSUSE Heroes?

**Comment by juliogonzalez** [comment]
@moio yes, let's close this. We already have this tracked internally. It's not a sumaform issue, and the agreement is to fix it at the openSUSE side.
